import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  addAccount,
  generateAccountNumber
} from "../../Services/AccountService";
import FinButton from "../../Components/Common/FinButton";

import "../../DisplayView.css";
import "../../FinCorePage.css";
import toast from "react-hot-toast";


const AccountEntry = () => {

  const navigate = useNavigate();

  const [errors, setErrors] = useState({});

  const [account, setAccount] = useState({
    accountNumber: 0,
    customerId: "",
    accountType: "Savings",
    balance: "5000",
    status: "A",
    accountopenDate: ""
  });

  const [newAccountNumber, setNewAccountNumber] = useState(0);
  const [flag, setFlag] = useState(false);
  const [openDate, setOpenDate] = useState(() => {
  const today = new Date();
  return today.toLocaleDateString("en-GB").replace(/\//g, "-");
});


useEffect(() => {
  loadAccountNumber();

  const today = new Date()
    .toLocaleDateString("en-GB")
    .replace(/\//g, "-");

  setOpenDate(today);

  setFlag(false);
}, []);


  const loadAccountNumber = () => {

    generateAccountNumber()
      .then((response) => {
        setNewAccountNumber(response.data);
      })
      .catch((error) => {

    console.log(error);

    toast.error(
        "Unable to generate account number"
    );

});
  };


  const onChangeHandler = (event) => {

    const { name, value } = event.target;

    setFlag(false);

    setAccount((previous) => ({
      ...previous,
      [name]: value
    }));

  };


  const saveAccount = (event) => {

    event.preventDefault();

    const accountToSave = {
      ...account,
      accountNumber: newAccountNumber,
      accountopenDate: openDate,
      balance: "5000"
    };

    addAccount(accountToSave)
.then((response) => {

    toast.success(
        "Account created successfully"
    );

    setFlag(true);

    setAccount({
        accountNumber: 0,
        customerId: "",
        accountType: "Savings",
        balance: "5000",
        status: "A",
        accountopenDate: ""
    });

    setOpenDate("");

    loadAccountNumber();

})
.catch((error) => {

    console.log(error);

    toast.error(
        "Account creation failed"
    );

});
  };
  


 const clearAll = (event) => {

    if (event) {
        event.preventDefault();
    }

    setAccount({
        accountNumber: 0,
        customerId: "",
        accountType: "Savings",
        balance: "5000",
        status: "A",
        accountopenDate: ""
    });

    setOpenDate("");
    setErrors({});
    setFlag(false);


    toast.success(
        "Account form cleared"
    );

};


  const handleValidation = (event) => {

    event.preventDefault();

    let tempErrors = {};
    let isValid = true;


    if (!account.customerId) {

      tempErrors.customerId =
        "Customer ID is required";

      isValid = false;

    }


    if (!openDate) {

      tempErrors.accountopenDate =
        "Opening Date is required";

      isValid = false;

    }


    setErrors(tempErrors);

    if (isValid) {

    saveAccount(event);

}
else {

    toast.error(
        "Please fill all required fields"
    );

}

  };


  const returnBack = () => {
    navigate("/admin-menu");
  };


  return (

    <div className="fincore-page">

     
      <div className="fincore-page-header">

        <h1 className="fincore-page-title">
          New Account Request
        </h1>

      </div>

      <div className="fincore-card account-form-card">

        <div className="fincore-card-header">

          <div className="fincore-card-icon">
            💳
          </div>

          <div>

            <h3>Account Information</h3>

            <p className="fincore-card-subtitle">
              Create a new customer bank account
            </p>

          </div>

        </div>


        <form onSubmit={handleValidation}>


          <div className="fincore-form-group">

            <label className="fincore-label">
              Account Number
            </label>

            <input
              type="text"
              className="fincore-input fincore-readonly"
              value={newAccountNumber}
              readOnly
            />

            <small className="fincore-helper">
              Automatically generated by FinCore
            </small>

          </div>

          <div className="fincore-form-group">

            <label className="fincore-label">
              Customer ID
            </label>

            <input
              type="number"
              name="customerId"
              className="fincore-input"
              placeholder="Enter Customer ID"
              value={account.customerId}
              onChange={onChangeHandler}
            />

            {errors.customerId && (

              <div className="fincore-error">
                ⚠ {errors.customerId}
              </div>

            )}

          </div>

          <div className="fincore-form-group">

            <label className="fincore-label">
              Account Type
            </label>

            <select
              name="accountType"
              className="fincore-select"
              value={account.accountType}
              onChange={onChangeHandler}
            >

              <option value="Savings">
                Savings Account
              </option>

              <option value="Current">
                Current Account
              </option>

            </select>

          </div>

          <div className="fincore-form-group">

            <label className="fincore-label">
              Opening Balance
            </label>

            <div className="fincore-money-input">

              <span>₹</span>

              <input
                type="text"
                className="fincore-input"
                value="5,000"
                readOnly
              />

            </div>

            <small className="fincore-helper">
              Fixed minimum opening balance
            </small>

          </div>

          <div className="fincore-form-group">

            <label className="fincore-label">
              Account Status
            </label>

            <div className="fincore-status-box">

              <span className="fincore-status-dot"></span>

              Active

            </div>

          </div>

          <div className="fincore-form-group">

            <label className="fincore-label">
              Account Opening Date
            </label>

          <input
  type="text"
  className="fincore-input fincore-readonly"
  value={openDate}
  readOnly
/>

            {errors.accountopenDate && (

              <div className="fincore-error">
                ⚠ {errors.accountopenDate}
              </div>

            )}

            <small className="fincore-helper">
              Enter date in DD-MM-YY format
            </small>

          </div>

          <div className="fincore-button-group">

            <FinButton
              type="submit"
              variant="primary"
            >
              ✓ Create Account
            </FinButton>


            <FinButton
              type="button"
              variant="gold"
              onClick={clearAll}
            >
              ↻ Reset
            </FinButton>


            <FinButton
              type="button"
              variant="secondary"
              onClick={returnBack}
            >
              ← Return Back
            </FinButton>

          </div>

        </form>

        {flag && (

          <div className="fincore-success-message">

            <span className="success-icon">
              ✓
            </span>

            <div>

              <strong>
                Account Created Successfully
              </strong>

              <p>
                The new bank account has been created successfully.
              </p>

            </div>

          </div>

        )}

      </div>

    </div>
  );
};

export default AccountEntry;